<?php
$LDPersonalPhysicalEval='Personal Physical Evaluation';
$LDVitalStatisticsCalc='Vital Statistics Calculator';
$LDEnterDetailsCorrectly='Please ensure that you enter the details correctly, you have JavaScript enabled and your browser supports it...';
$LDYourAgeIs='Your age (in years) is';
$LDYouAreA='You are a?';
$LDMale='Male';
$LDFemale='Female';
$LDYourWeightKgs='Your weight (in Kgs) is';
$LDYourWeightLbs='Your weight (in Lbs) is';
$LDYourWaistSizeCm='Your waist size (in cms) is';
$LDYourWaistSizeInches='Your waist size (in inches) is';
$LDYourHeightCm='Your height (in cms) is';
$LDYourHeightInches='Your height (in feet and inches) is';
$LDYourPulseRate='Your Pulse Rate is';

$LDBeatsPerMinute='beats per minute';
$LDYourBloodPresure='Your Blood Pressure (mm of Hg) is';
$LDSystolic='systolic';
$LDDiastolic='diastolic';
$LDCalculate='Calculate';
$LDClearForm='Clear Form';
$LDFillInText='Fill in only one weight (either in Kgs or in Lbs) and height (either in cms or feet and inches).';
$LDTheProgrammeCalculateAutomatically='The programme will automatically calculate the other';

$LDIfInDoubtText='If in doubt, ask a nurse or para-medic to help you out with the figures';
$LDResultsInterpretations='Results and their Interpretations';
$LDYoungMen='young man';
$LDTheseBMICalculations='These BMI calculations are not applicable to you';
$LDman='man';
$LDTheBMICalculations='The BMI calculations are applicable to you:';
$LDYoungLady='young lady';
$LDlady='lady';
$LDunderweight='underweight';
$LDwithinRange='within healthy range';
$LDoverweight='overweight';
$LDsignificantlyoverweight='significantly overweight';
$LDobese='obese';
$LDNotOverweight='You are not overweight';
$LDVitalCalcTxt[0]='<font color=\"FF9900\">You are overweight, and are at an increased risk, <br />particulary if you have type 2 diabetes and/or hypertension (high blood pressure) and/or heart disease</font>';
$LDVitalCalcTxt[1]='<font color=\"FF9900\">You are overweight, and are at a high risk, <br />particulary if you have type 2 diabetes and/or hypertension (high blood pressure) and/or heart disease</font>';
$LDVitalCalcTxt[2]='<font color=\"FFCC00\">You appear to have class I obesity, and are at a high risk, <br />particulary if you have type 2 diabetes and/or hypertension (high blood pressure) and/or heart disease</font>';
$LDVitalCalcTxt[3]='<font color=\"FFCC00\">You appear to have class I obesity, and are at a very high risk, <br />particulary if you have type 2 diabetes and/or hypertension (high blood pressure) and/or heart disease</font>';
$LDVitalCalcTxt[4]='<font color=\"FF6600\">You appear to have class II obesity, and are at a very high risk, <br />particulary if you have type 2 diabetes and/or hypertension (high blood pressure) and/or heart disease</font>';
$LDVitalCalcTxt[5]='<font color=\"FF0000\">You appear to have class III obesity, and are at an extremely high risk,<br /> particulary if you have type 2 diabetes and/or hypertension (high blood pressure) and/or heart disease</font>';
$LDVitalCalcTxt[6]='and this is your <font color=\"darkorchid\">ideal body weight</font>';
$LDVitalCalcTxt[7]='while your ideal body weight should be';
$LDKgsor='Kgs or';
$LDlbs='lbs';
$LDVitalCalcTxt[8]='<font color=\"red\">high</font> for it should be no more than 50';
$LDVitalCalcTxt[8]='<font color=\"blue\">low</font> for it should be no less than 40';
$LDVitalCalcTxt[10]='within normal limits';
$LDVitalCalcTxt[11]='complete heart block';
$LDbradycardia='bradycardia';
$LDSinusTachycardia='sinus tachycardia';
$LDTachycardia='tachycardia';
$LDVitalCalcTxt[12]='supraventricular or ventricluar tachycardia';
$LDVitalCalcTxt[13]='a pulse rate within normal range';
$LDVitalCalcTxt[14]='within normal limits';
$LDhypotensive='hypotensive';
$LDmildlyhypertensive='mildly hypertensive';
$LDmoderatelyhypertensive='moderately hypertensive';
$LDseverelyhypertensive='severely hypertensive';
$LDmoderatelyhypertensive='moderately hypertensive';
$LDunderweight='underweight';
$LDpronetohealthrisks='prone to health risks';
$LDVitalCalcTxt[15]=' and you are <font color=\"red\">at a very high for development of heart diseases</font>';
$LDVitalCalcTxt[16]=' and you are <font color=\"red\">prone to health risks</font>';
$LDVitalCalcTxt[17]=' and you are <font color=\"green\">fine</font>';
$LDVitalCalcTxt[18]='this value is <font color=\"red\">high</font> for it should not be more than 10';
$LDVitalCalcTxt[19]='this value is <font color=\"blue\">low</font> for it should not be less than 10';
$LDVitalCalcTxt[20]='this value is <font color=\"green\">within normal limits';
$LDVitalCalcTxt[21]='<font color=\"red\">secondary causes of hypertension<br /><b>See your physician without delay!</b></font>';
$LDidiopathicHypertension='idiopathic causes of hypertension';
$LDVitalCalcTxt[22]='no blood pressure problems';
$LDVitalCalcTxt[23]='You are a';
$LDVitalCalcTxt[24]='and your age is';
$LDyears='years';
$LDWeight='Weight';
$LDVitalCalcTxt[25]='You should maintain';
$LDVitalCalcTxt[26]='body weight between';
$LDand='and';
$LDVitalCalcTxt[27]='and should NOT cross';
$LDVitalCalcTxt[28]='This is equivalent to';
$LDVitalCalcTxt[29]='in lbs respectively';
$LDVitalCalcTxt[30]='Height and Body Mass Index';
$LDVitalCalcTxt[31]='Your height is';
$LDcmsor='cms or';
$LDinches='inches';
$LDVitalCalcTxt[32]='body mass index is';
$LDVitalCalcTxt[33]='Required Calories';
$LDVitalCalcTxt[34]='You require to consume between';
$LDVitalCalcTxt[35]='KCalories per day to maintain/achieve your ideal body weight';
$LDVitalCalcTxt[36]='Body Surface Area and Fat Percentage';
$LDVitalCalcTxt[37]='Your body surface area is';
$LDVitalCalcTxt[38]='Your body fat percentage is';
$LDVitalCalcTxt[39]='and this indicates that you are';
$LDBloodPressure='Blood Pressure';
$LDVitalCalcTxt[40]='Your blood pressure is';
$LDtorr='torr';
$LDkPa='kPa*';
$LDVitalCalcTxt[41]='This means that you have a blood pressure that is';
$LDVitalCalcTxt[42]='and you appear to have';
$LDVitalCalcTxt[43]='Your pulse pressure is';
$LDVitalCalcTxt[44]='torr and this figure is';
$LDPulseRate='Pulse Rate';
$LDVitalCalcTxt[45]='Your pulse rate is';
$LDVitalCalcTxt[46]='beats per minute and this means that you have';
$LDVitalCalcTxt[47]='Your target heart rate is';
$LDbeatsperminute='beats per minute';
$LDVitalCalcTxt[48]='You should achieve at least';
$LDVitalCalcTxt[49]='heart beats per minute when you are exercising at your peak';
$LDBasalMetabolicRate='Basal Metabolic Rate';
$LDVitalCalcTxt[50]='Your basal metabolic rate is';
$LDVitalCalcTxt[51]='1 torr = 1 mmHg, *kPa = kilo Pascals';
$LDVitalCalcTxt[52]='The target heart rate is not useful for children';
$LDVitalCalcTxt[53]='The obesity calculator does not take into account the waist to hip ratio, currently';
$LDVitalCalcTxt[54]='Re-calculate';
$LDVitalCalcTxt[55]='Your weight is';
$LDKgs='Kgs';
$LDor='or';
?>